hlq=YOUR_HLQ

dbrmPDS = ${hlq}.DBRM
loadPDS = ${hlq}.LOAD
cicsPDS = ${hlq}.CICS
subPDS = ${hlq}.SUB
objPDS = ${hlq}.OBJ
bindcardPDS = ${hlq}.BINDCARD
listPDS = ${hlq}.LIST

# CICS libraries
CICSLIB = SYS1.CICSTS61
CICSALIAS = CICSDEV

# DB2 libraries
SDSNLOAD = SYS1.DSNDB2A.SDSNLOAD

# Symbolic SYSLIB datasets
CAIEZTLIB = SYS1.EZI.CBAALOAD
CAIEZTMAC = SYS1.EZI.CBAAMAC
CAILIB = CAI.CAILIB
CAIMACACF = SYS1.ACF.CAX1MAC0
CAIMACCA1 = SYS1.CA1.CTAPMAC
COBCOMP = SYS1.ADCOB.SIGYCOMP
COB2LIB = SYS1.COB2LIB
DBALIB = SYS1.DBALIB
DBAT = ACT.DBAT
QASLOAD = QAS.V3R1M2.CLIENT.LOAD
SCEECICS = SYS1.SCEECICS
SCEELKED = SYS1.SCEELKED
SCEEMAC = SYS1.SCEEMAC
SCEEMSGP = SYS1.SCEEMSGP
SCEERUN = SYS1.SCEERUN
SCSQLOAD = SYS1.MQM.SCSQLOAD


