# Script Mappings for all application programs
dbb.scriptMapping = Assembler.groovy :: **/*.asm
dbb.scriptMapping = BMS.groovy :: **/*.bms
dbb.scriptMapping = Cobol.groovy :: **/*.cbl
dbb.scriptMapping = LinkEdit.groovy :: **/*.lnk
dbb.scriptMapping = PlI.groovy :: **/*.pli

# This property file can also be used to set values of hasDB2/hasCICS for the application manually.
# Instead of scanning the source code for DB2/CICS statements, the build will use the values set here.  This can be useful if the source code is not available to scan, or if the source code is not in a format that can be scanned (e.g. pre-processed source code).
# This actually speeds up the build process, as the scanning of source code can take a long time for large applications.

# Cobol 
hasDB2=true :: **/COBB/*.cbl
hasCICS=true :: **/COBC/*.cbl

hasDB2=false :: **/COBC/*.cbl
hasCICS=false :: **/COBB/*.cbl