#-------------------------------------------------------------------
# typeseq.properties - Endevor Type Sequence for DBB Build  
#-------------------------------------------------------------------
# Mirrors the Endevor Type Sequence for DBB Build.  This file is used to determine the order of processing for Endevor types during a build.  The order of the types in this file should match the order of the types in the Endevor Type Sequence.
# --> build.groovy reads these values to sort the source files into correct order for processing before any lang scripts are executed.  If the order of the types in this file does not match the order of the types in the Endevor Type Sequence, then the build may fail due to dependencies between types.
# So that copybook are always processed before the programs that use them, the copybook type should be listed first in this file.  The order of the other types is not as important, but it is recommended to keep the order consistent with the Endevor Type Sequence.
# Hence dependencies are satisfied in the right order 
#
# Key Format : typeSequence.<FOLDERNAME> = <sequence number>
#
# To override for a specific application without touching this file,
# Add the same key in :
#    <appName>/application-conf/typseq.properties
#
# Files whose folder has no entry here get seq=999 and are processed last.  This is to ensure that any new types added to Endevor are processed after the known types.
# COPYbooks and includes are processed first
typeSequence.ASMCOPY = 10
typeSequence.COBCOPY = 20
typeSequence.PL1COPY = 30
typeSequence.MAPCOPY = 40
typeSequence.PSBCOPY = 50
typeSequence.H = 60
typeSequence.MACRO = 70
typeSequence.PRE = 80

# MAP types 
typeSequence.MAPBMS = 90
typeSequence.ACT = 100

# Program types
typeSequence.ASMB = 110
typeSequence.ASMC = 120   
typeSequence.ASMI = 130   

typeSequence.COBB = 140
typeSequence.COBC = 150 
typeSequence.COBI = 160
typeSequence.COBSP = 170
typeSequence.COBD = 180
typeSequence.SQLB = 185

typeSequence.PL1B = 190
typeSequence.PL1C = 200
typeSequence.PL1I = 210

typeSequence.c=220
typeSequence.C37B=230
typeSequence.C37C=240
typeSequence.C37I=245

typeSequence.EZTB=250

typeSequence.LNKS=260
typeSequence.LNKB=270
typeSequence.LNKC=280
typeSequence.LNKI=290
typeSequence.LNKSP=300
typeSequence.LNKD=310
typeSequence.LINKC370=320